// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJa-PqN2nIMq03Tj3-QacMDF67LjS7at8',
    appId: '1:511032183989:web:a9ff0a8b5ab1470f4d82fc',
    messagingSenderId: '511032183989',
    projectId: 'telead-ad2b0',
    authDomain: 'telead-ad2b0.firebaseapp.com',
    storageBucket: 'telead-ad2b0.appspot.com',
    measurementId: 'G-6J3SNKSGHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIN3XAunH3XdmCQ-RpVAMB2j8yCoX0jv4',
    appId: '1:511032183989:android:8b91777b906430f34d82fc',
    messagingSenderId: '511032183989',
    projectId: 'telead-ad2b0',
    storageBucket: 'telead-ad2b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZx55NG7PEd3Q2JITe5olSytpXm3L3ZE',
    appId: '1:511032183989:ios:0bb1711aaf3b75e54d82fc',
    messagingSenderId: '511032183989',
    projectId: 'telead-ad2b0',
    storageBucket: 'telead-ad2b0.appspot.com',
    androidClientId: '511032183989-7f0mn3oqdseptfmc1jsqdd4up6fi7d8v.apps.googleusercontent.com',
    iosClientId: '511032183989-dqs7sfj06h5b5hg30n6ncbn34rbrc5hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.telead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZx55NG7PEd3Q2JITe5olSytpXm3L3ZE',
    appId: '1:511032183989:ios:0bb1711aaf3b75e54d82fc',
    messagingSenderId: '511032183989',
    projectId: 'telead-ad2b0',
    storageBucket: 'telead-ad2b0.appspot.com',
    androidClientId: '511032183989-7f0mn3oqdseptfmc1jsqdd4up6fi7d8v.apps.googleusercontent.com',
    iosClientId: '511032183989-dqs7sfj06h5b5hg30n6ncbn34rbrc5hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.telead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJa-PqN2nIMq03Tj3-QacMDF67LjS7at8',
    appId: '1:511032183989:web:ae9d5dae2ea8a4484d82fc',
    messagingSenderId: '511032183989',
    projectId: 'telead-ad2b0',
    authDomain: 'telead-ad2b0.firebaseapp.com',
    storageBucket: 'telead-ad2b0.appspot.com',
    measurementId: 'G-8K2EB5LV0E',
  );
}